databases:
  - name: electronics-shop-db
    plan: free
    databaseName: electronics_shop
    user: electronics_shop_user

services:
  - type: web
    name: electrical-shop-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: electronics-shop-db
          property: connectionURI
      - key: PYTHON_VERSION
        value: "3.11.0"
